### ISSUE TITLE
Twillio outbound caller ID issue

### ISSUE THREAD

**Issue by joseamt** [TwilioDevEd/api-snippets#474]
I have to add user as an outbound caller in to my  twillio account. The following code is unsing to add a user to my account  
` const accountSid = 'xxxxxxxxxxxxxxxxxxxxxxxxx';
const authToken = 'xxxxxxxxxxxxxxxxxxxxxxxxxx';
const client = require('twilio')(accountSid, authToken);

client.outgoingCallerIds
  .create({
    friendlyName: 'My Home Phone Number',
    phoneNumber: '+14158675309',
  })
  .then((callerId) => process.stdout.write(callerId.sid)); `
but its giving an error message like

.create({
   ^
TypeError: client.outgoingCallerIds.create is not a function
    at Object.<anonymous> (/home/jose/test/twillio/callerid.js:6:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by po5i** [comment]
It's recommended to use the latest version for the library. You can use this snippet instead:
[list-post-example-1.3.x.js](https://github.com/TwilioDevEd/api-snippets/blob/master/rest/outgoing-caller-ids/list-post-example-1/list-post-example-1.3.x.js)
